#!/usr/bin/env python3
"""Generate the immutable TurnSafe configure provenance and C++ header."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import sys
from typing import Any, Dict, Mapping, Optional, Sequence


SOURCE_SCHEMA = "turnsafe.source_snapshot.v1"
CONFIGURE_SCHEMA = "turnsafe.configure_provenance.v1"


class ProvenanceError(RuntimeError):
    """A fail-closed provenance-generation error."""


def _canonical_bytes(value: Mapping[str, Any]) -> bytes:
    return json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("ascii")


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while True:
            block = stream.read(1024 * 1024)
            if not block:
                break
            digest.update(block)
    return digest.hexdigest()


def _load_snapshot(path: Path) -> Dict[str, Any]:
    value = json.loads(path.read_text(encoding="ascii"))
    if not isinstance(value, dict) or value.get("schema_version") != SOURCE_SCHEMA:
        raise ProvenanceError("invalid source snapshot schema")
    claimed = value.get("aggregate_source_snapshot_sha256")
    body = dict(value)
    body.pop("aggregate_source_snapshot_sha256", None)
    actual = hashlib.sha256(_canonical_bytes(body)).hexdigest()
    if claimed != actual:
        raise ProvenanceError("source snapshot aggregate mismatch")
    for key in ("head_sha", "head_tree", "source_dirty"):
        if key not in value:
            raise ProvenanceError("source snapshot is missing {}".format(key))
    return value


def _write_atomic(path: Path, payload: str) -> None:
    path = path.resolve(strict=False)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp.{}".format(os.getpid()))
    try:
        with temporary.open("x", encoding="ascii", newline="\n") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(str(temporary), str(path))
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate(args: argparse.Namespace) -> Dict[str, Any]:
    snapshot_path = Path(args.source_snapshot).resolve(strict=True)
    schema_path = Path(args.schema).resolve(strict=True)
    snapshot = _load_snapshot(snapshot_path)
    configuration = {
        "build_type": args.build_type,
        "catkin_enable_testing": args.catkin_enable_testing,
        "ceres_dir": args.ceres_dir,
        "cmake_cxx_flags_cache": args.cmake_cxx_flags_cache,
        "cmake_cxx_flags_effective": args.cmake_cxx_flags_effective,
        "cmake_generator": args.cmake_generator,
        "cmake_source_directory": str(
            Path(args.cmake_source_directory).resolve(strict=True)
        ),
        "cmake_binary_directory": str(
            Path(args.cmake_binary_directory).resolve(strict=True)
        ),
        "cmake_version": args.cmake_version,
        "cxx_compiler": args.cxx_compiler,
        "cxx_compiler_id": args.cxx_compiler_id,
        "cxx_compiler_version": args.cxx_compiler_version,
        "enable_ros": args.enable_ros,
    }
    descriptor: Dict[str, Any] = {
        "source": {
            "head_sha": snapshot["head_sha"],
            "head_tree": snapshot["head_tree"],
            "source_dirty": bool(snapshot["source_dirty"]),
            "source_snapshot_sha256": snapshot[
                "aggregate_source_snapshot_sha256"
            ],
            "tracked_diff_sha256": snapshot["tracked_diff_sha256"],
            "status_porcelain_sha256": snapshot[
                "status_porcelain_sha256"
            ],
        },
        "diagnostic_schema_sha256": _sha256_file(schema_path),
        "configuration": configuration,
    }
    build_provenance_id = hashlib.sha256(
        _canonical_bytes(descriptor)
    ).hexdigest()
    manifest: Dict[str, Any] = {
        "schema_version": CONFIGURE_SCHEMA,
        "build_provenance_id": build_provenance_id,
        "descriptor": descriptor,
        "source_snapshot": snapshot,
    }
    manifest_payload = json.dumps(manifest, sort_keys=True, indent=2) + "\n"
    manifest_sha256 = hashlib.sha256(manifest_payload.encode("ascii")).hexdigest()
    header = """/* Generated by generate_build_provenance.py; do not edit. */
#ifndef OV_MSCKF_TURNSAFE_BUILD_PROVENANCE_GENERATED_H
#define OV_MSCKF_TURNSAFE_BUILD_PROVENANCE_GENERATED_H
namespace ov_msckf { namespace turnsafe_build {
static constexpr const char kSourceSha[] = %s;
static constexpr const char kSourceTree[] = %s;
static constexpr const char kSourceSnapshotSha256[] = %s;
static constexpr bool kSourceDirty = %s;
static constexpr const char kBuildProvenanceId[] = %s;
static constexpr const char kConfigureManifestSha256[] = %s;
static constexpr const char kDiagnosticSchemaSha256[] = %s;
} } // namespace ov_msckf::turnsafe_build
#endif
""" % (
        _cpp_string(str(snapshot["head_sha"])),
        _cpp_string(str(snapshot["head_tree"])),
        _cpp_string(str(snapshot["aggregate_source_snapshot_sha256"])),
        "true" if snapshot["source_dirty"] else "false",
        _cpp_string(build_provenance_id),
        _cpp_string(manifest_sha256),
        _cpp_string(str(descriptor["diagnostic_schema_sha256"])),
    )
    _write_atomic(Path(args.output_manifest), manifest_payload)
    _write_atomic(Path(args.output_header), header)
    return manifest


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-snapshot", required=True)
    parser.add_argument("--schema", required=True)
    parser.add_argument("--output-header", required=True)
    parser.add_argument("--output-manifest", required=True)
    parser.add_argument("--build-type", required=True)
    parser.add_argument("--cxx-compiler", required=True)
    parser.add_argument("--cxx-compiler-id", required=True)
    parser.add_argument("--cxx-compiler-version", required=True)
    parser.add_argument("--cmake-generator", required=True)
    parser.add_argument("--cmake-version", required=True)
    parser.add_argument("--cmake-cxx-flags-cache", required=True)
    parser.add_argument("--cmake-cxx-flags-effective", required=True)
    parser.add_argument("--ceres-dir", required=True)
    parser.add_argument("--enable-ros", required=True)
    parser.add_argument("--catkin-enable-testing", required=True)
    parser.add_argument("--cmake-source-directory", required=True)
    parser.add_argument("--cmake-binary-directory", required=True)
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    try:
        generate(_parser().parse_args(argv))
    except (OSError, ValueError, KeyError, ProvenanceError) as exc:
        print("BUILD_PROVENANCE_ERROR: {}".format(exc), file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
