#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Synthetic corruption tests for the production CP2 readiness verifier.

The fixture is deliberately assembled from generated bytes under ``/tmp``.
It never reads the dataset registry, a bag, ground truth, or a repository
build/results tree.  Independent encoders build the retained context,
snapshots, archive, command environments, and Git streams before the real
production verifier consumes them.
"""

from __future__ import annotations

import contextlib
import copy
import hashlib
import importlib.util
import io
import json
import os
from pathlib import Path
import subprocess
import sys
import tarfile
import tempfile
import unittest
from unittest import mock


CP2_DIRECTORY = Path(__file__).resolve().parents[1]
VERIFY_REPORT_PATH = CP2_DIRECTORY / "verify_report.py"
VERIFY_REPORT_SPEC = importlib.util.spec_from_file_location(
    "cp2_actual_readiness_binding_test_verify_report", VERIFY_REPORT_PATH
)
verify_report = importlib.util.module_from_spec(VERIFY_REPORT_SPEC)
sys.modules[VERIFY_REPORT_SPEC.name] = verify_report
VERIFY_REPORT_SPEC.loader.exec_module(verify_report)
RUN_RECORDED_PATH = CP2_DIRECTORY / "run_recorded_parity.py"
RUN_RECORDED_SPEC = importlib.util.spec_from_file_location(
    "cp2_actual_readiness_binding_test_run_recorded", RUN_RECORDED_PATH
)
run_recorded = importlib.util.module_from_spec(RUN_RECORDED_SPEC)
sys.modules[RUN_RECORDED_SPEC.name] = run_recorded
RUN_RECORDED_SPEC.loader.exec_module(run_recorded)


def canonical_json(value):
    return json.dumps(
        value,
        allow_nan=False,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def sha256(content):
    return hashlib.sha256(content).hexdigest()


def git_blob(content):
    return hashlib.sha1(
        b"blob " + str(len(content)).encode("ascii") + b"\0" + content
    ).hexdigest()


def lp(content):
    return len(content).to_bytes(8, "big") + content


def command_environment_sha256(mapping):
    records = sorted(
        ((name.encode("utf-8"), value.encode("utf-8"))
         for name, value in mapping.items()),
        key=lambda item: item[0],
    )
    payload = bytearray(b"SchurVIO-CP2-command-environment-v1\0")
    payload.extend(len(records).to_bytes(8, "big"))
    for name, value in records:
        payload.extend(lp(name))
        payload.extend(lp(value))
    return sha256(bytes(payload))


def utc(second):
    if not 0 <= second < 60:
        raise ValueError("synthetic UTC second leaves its fixed minute")
    return "2026-01-01T00:00:{:02d}.000000Z".format(second)


def encode_snapshot(root_tag, exists, entries, context=None):
    payload = bytearray(b"SchurVIO-CP2-readiness-snapshot-v1\0")
    payload.extend(lp(root_tag.encode("ascii")))
    payload.extend(b"\1" if exists else b"\0")
    ordered = sorted(entries, key=lambda item: item["path"].encode("utf-8"))
    payload.extend(len(ordered).to_bytes(8, "big"))
    for entry in ordered:
        payload.extend(lp(entry["path"].encode("utf-8")))
        payload.extend(entry["entry_type"].encode("ascii"))
        payload.extend(entry["mode"].to_bytes(8, "big"))
        payload.extend(entry["size"].to_bytes(8, "big"))
        payload.extend(bytes.fromhex(entry["sha256"]))
    if root_tag in ("source", "post_lock"):
        if context is None:
            raise ValueError("source-like snapshot requires a context")
        payload.extend(bytes.fromhex(context["commit"]))
        payload.extend(bytes.fromhex(context["tree"]))
        payload.extend(bytes.fromhex(context["index_tree"]))
        payload.extend(lp(b""))
        for entrypoint in context["entrypoints"]:
            payload.extend(lp(entrypoint["path"].encode("utf-8")))
            payload.extend(bytes.fromhex(entrypoint["git_blob"]))
            payload.extend(bytes.fromhex(entrypoint["sha256"]))
    return bytes(payload)


def passing_self_test_result(entrypoint, names, index):
    cases = []
    for case_index, name in enumerate(names):
        negative = name != "valid_minimal_fixture"
        cases.append({
            "index": case_index,
            "name": name,
            "expected_rejection": negative,
            "observed_rejection": negative,
            "passed": True,
        })
    return {
        "schema_version": 1,
        "record_type": "self_test_result",
        "entrypoint": entrypoint,
        "temporary_root": "/tmp/cp2-actual-readiness-selftest-{}".format(index),
        "bag_provider_calls": 0,
        "cases": cases,
        "case_count": len(cases),
        "passed": True,
    }


class ActualReadinessFixture:
    """One valid production-verifier readiness slice and mutation helpers."""

    APPROVAL_PATH = "docs/synthetic_cp2_approval.txt"
    SOURCE_ARCHIVE = "source_snapshot.tar"

    def __init__(self, parent):
        self.parent = Path(parent)
        self.artifact = self.parent / "artifact"
        self.artifact.mkdir(mode=0o700)
        self.commit = "1" * 40
        self.tree = "2" * 40
        self.manifest = {}
        self._build_context_and_archive()
        self._build_snapshots()
        self._build_git_evidence()
        self._build_self_tests()
        self._build_unit_evidence()
        self._build_barrier_and_provenance()

    def _write(self, relative, content, mode=0o444):
        path = self.artifact.joinpath(*relative.split("/"))
        path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        if path.exists() or path.is_symlink():
            if not path.is_symlink():
                path.chmod(0o600)
            path.unlink()
        path.write_bytes(content)
        path.chmod(mode)
        self.manifest[relative] = sha256(content)
        return path

    def _build_context_and_archive(self):
        source_paths = set(verify_report.READINESS_ENTRYPOINTS)
        source_paths.update({
            "scripts/cp2/cp2_readiness.py",
            "scripts/cp2/cp2_schema.py",
            "scripts/cp2/cp2_sequence_math.py",
            "scripts/cp2/verify_report.py",
        })
        source_paths.update(verify_report._ACTUAL_LOCAL_MODULE_PATHS.values())
        self.source_contents = {
            path: (CP2_DIRECTORY / Path(path).name).read_bytes()
            for path in source_paths
        }
        self.source_contents[verify_report.PREAUTHORIZATION_REGISTRY_PATH] = (
            b"SYNTHETIC-OPAQUE-REGISTRY-SENTINEL:\xff:\x00\n"
        )
        self.source_contents[self.APPROVAL_PATH] = (
            b"synthetic approval anchor; no recorded-data authority\n"
        )
        repository_root = CP2_DIRECTORY.parents[1]
        for path in verify_report.FROZEN_CP2_COMPLETION_AUTHORIZATION_BINDING:
            self.source_contents[path] = (repository_root / path).read_bytes()
        entries = []
        for path in sorted(self.source_contents, key=lambda value: value.encode("utf-8")):
            content = self.source_contents[path]
            mode = 0o100755 if path.endswith("run_unit_gate.sh") else 0o100644
            entries.append({
                "git_blob": git_blob(content),
                "mode": mode,
                "path": path,
                "sha256": sha256(content),
                "size": len(content),
            })
        by_path = {entry["path"]: entry for entry in entries}
        entrypoints = []
        for path in verify_report.READINESS_ENTRYPOINTS:
            entry = by_path[path]
            entrypoints.append({
                "git_blob": entry["git_blob"],
                "mode": entry["mode"],
                "path": path,
                "regular_nonsymlink": True,
                "sha256": entry["sha256"],
            })
        self.context = {
            "branch": verify_report.EXPECTED_BRANCH,
            "commit": self.commit,
            "entries": entries,
            "entrypoints": entrypoints,
            "index_tree": self.tree,
            "record_type": verify_report.PREVALIDATED_SOURCE_RECORD_TYPE,
            "schema_version": 1,
            "status_porcelain_v1_hex": "",
            "tree": self.tree,
        }
        context_bytes = canonical_json(self.context)
        self._write("readiness/source_context.json", context_bytes)
        self._write_source_archive()
        approval = by_path[self.APPROVAL_PATH]
        self.approval_binding = {
            self.APPROVAL_PATH: {
                "sha256": approval["sha256"],
                "git_blob": approval["git_blob"],
            }
        }
        self.source_inputs = frozenset(self.source_contents)
        self.contract_inputs = frozenset((
            self.APPROVAL_PATH,
            *verify_report.FROZEN_CP2_COMPLETION_AUTHORIZATION_BINDING,
        ))

    def _write_source_archive(self):
        archive_path = self.artifact / self.SOURCE_ARCHIVE
        archive_path.parent.mkdir(parents=True, exist_ok=True)
        with tarfile.open(
            str(archive_path),
            mode="w:",
            format=tarfile.PAX_FORMAT,
            pax_headers={"comment": self.commit},
        ) as archive:
            directories = set()
            for path in self.source_contents:
                parts = path.split("/")
                directories.update(
                    "/".join(parts[:length]) for length in range(1, len(parts))
                )
            for directory in sorted(directories, key=lambda value: value.encode("utf-8")):
                member = tarfile.TarInfo(directory)
                member.type = tarfile.DIRTYPE
                member.mode = 0o775
                member.uid = 0
                member.gid = 0
                member.size = 0
                member.mtime = 0
                member.pax_headers = {"comment": self.commit}
                archive.addfile(member)
            by_path = {entry["path"]: entry for entry in self.context["entries"]}
            for path in sorted(self.source_contents, key=lambda value: value.encode("utf-8")):
                content = self.source_contents[path]
                member = tarfile.TarInfo(path)
                member.mode = 0o775 if by_path[path]["mode"] == 0o100755 else 0o664
                member.uid = 0
                member.gid = 0
                member.size = len(content)
                member.mtime = 0
                member.pax_headers = {"comment": self.commit}
                archive.addfile(member, io.BytesIO(content))
        archive_path.chmod(0o444)
        self.manifest[self.SOURCE_ARCHIVE] = sha256(archive_path.read_bytes())

    def _build_snapshots(self):
        source_entries = [
            {
                "path": entry["path"],
                "entry_type": "f",
                "mode": entry["mode"],
                "size": entry["size"],
                "sha256": entry["sha256"],
            }
            for entry in self.context["entries"]
        ]
        source = encode_snapshot("source", True, source_entries, self.context)
        post_lock = encode_snapshot("post_lock", True, source_entries, self.context)
        build_entries = (
            {"path": "cache", "entry_type": "d", "mode": 0o755,
             "size": 0, "sha256": "0" * 64},
            {"path": "cache/a.bin", "entry_type": "f", "mode": 0o644,
             "size": 1, "sha256": sha256(b"a")},
            {"path": "link", "entry_type": "l", "mode": 0o777,
             "size": 6, "sha256": sha256(b"target")},
        )
        build = encode_snapshot("build", True, build_entries)
        results = encode_snapshot("results", True, ())
        testing = encode_snapshot("testing", False, ())
        self.snapshot_bytes = {
            "source_before": source,
            "build_before": build,
            "results_before": results,
            "testing_before": testing,
            "source_after": source,
            "build_after": build,
            "results_after": results,
            "testing_after": testing,
            "post_lock": post_lock,
            "post_unit": post_lock,
        }
        for name, content in self.snapshot_bytes.items():
            self._write("readiness/{}.bin".format(name), content)

    @staticmethod
    def _git_prefix():
        options = (
            "color.ui=false", "core.attributesFile=/dev/null",
            "core.commitGraph=false", "core.excludesFile=/dev/null",
            "core.fileMode=true", "core.fsmonitor=false",
            "core.hooksPath=/dev/null", "core.ignoreCase=false",
            "core.sparseCheckout=false", "core.sparseCheckoutCone=false",
            "core.untrackedCache=false", "diff.external=", "pager.status=false",
            "protocol.allow=never", "protocol.file.allow=never",
            "status.submoduleSummary=false", "submodule.recurse=false",
        )
        prefix = [
            "/usr/bin/git", "--no-pager", "--no-optional-locks",
            "--git-dir=/proc/self/fd/4", "--work-tree=/proc/self/fd/3",
        ]
        for option in options:
            prefix.extend(("-c", option))
        return prefix

    def _build_git_evidence(self):
        self.git_environment = {
            "GIT_ALLOW_PROTOCOL": "none",
            "GIT_ATTR_NOSYSTEM": "1",
            "GIT_CONFIG_NOSYSTEM": "1",
            "GIT_LITERAL_PATHSPECS": "1",
            "GIT_NO_LAZY_FETCH": "1",
            "GIT_NO_REPLACE_OBJECTS": "1",
            "GIT_OPTIONAL_LOCKS": "0",
            "GIT_PAGER": "",
            "GIT_PROTOCOL_FROM_USER": "0",
            "GIT_TERMINAL_PROMPT": "0",
            "HOME": "/tmp/schurvio-cp2-readiness-synthetic/git-home",
            "LANG": "C.UTF-8",
            "LC_ALL": "C.UTF-8",
            "PATH": "/usr/bin:/bin",
            "TMPDIR": "/tmp/schurvio-cp2-readiness-synthetic/git-tmp",
        }
        environment_sha = command_environment_sha256(self.git_environment)
        self.git_environment_record = {
            "environment_id": "readiness_git_v1",
            "variables": [
                {"name": name, "value": self.git_environment[name]}
                for name in sorted(
                    self.git_environment, key=lambda value: value.encode("utf-8")
                )
            ],
            "canonical_sha256": environment_sha,
        }
        triplet = (
            ("status", "--porcelain=v1", "-z", "--untracked-files=all"),
            ("rev-parse", "--verify", "HEAD"),
            ("rev-parse", "--verify", "HEAD^{tree}"),
        )
        suffixes = [
            ("ls-files", "--stage", "-z"),
            ("ls-files", "--others", "-z"),
            ("cat-file", "--batch"),
            triplet[0],
            ("ls-files", "--others", "--ignored", "--exclude-standard", "-z"),
            triplet[1],
            triplet[2],
            ("merge-base", "--is-ancestor", verify_report.CP1_AUTHORIZATION_COMMIT,
             "HEAD"),
        ] + list(triplet) * 4
        stage = b"".join(
            (
                "{:o} {} 0\t".format(entry["mode"], entry["git_blob"]).encode("ascii")
                + entry["path"].encode("utf-8") + b"\0"
            )
            for entry in self.context["entries"]
        )
        other = b"build/cache/a.bin\0build/link\0"
        ignored = b"build/cache/a.bin\0"
        outputs = [stage, other, None, b"", ignored,
                   (self.commit + "\n").encode("ascii"),
                   (self.tree + "\n").encode("ascii"), b""]
        for suffix in suffixes[8:]:
            if suffix == triplet[0]:
                outputs.append(b"")
            elif suffix == triplet[1]:
                outputs.append((self.commit + "\n").encode("ascii"))
            else:
                outputs.append((self.tree + "\n").encode("ascii"))
        cat_request = b"".join(
            (entry["git_blob"] + "\n").encode("ascii")
            for entry in self.context["entries"]
        )
        cat_stdout = b"".join(
            (
                "{} blob {}\n".format(entry["git_blob"], entry["size"]).encode("ascii")
                + self.source_contents[entry["path"]] + b"\n"
            )
            for entry in self.context["entries"]
        )
        command_seconds = list(range(0, 22, 2)) + list(range(32, 44, 2)) + [46, 48, 50]
        empty_sha = sha256(b"")
        self.git_commands = []
        for index, (suffix, output, second) in enumerate(
            zip(suffixes, outputs, command_seconds)
        ):
            relative = None
            output_sha = sha256(cat_stdout) if index == 2 else sha256(output)
            if index != 2:
                relative = "readiness/git/{:02d}.stdout".format(index)
                self._write(relative, output)
            self.git_commands.append({
                "command_index": index,
                "argv": self._git_prefix() + list(suffix),
                "cwd": "/proc/self/fd/3",
                "environment_sha256": environment_sha,
                "stdin_sha256": sha256(cat_request) if index == 2 else empty_sha,
                "stdout_sha256": output_sha,
                "stderr_sha256": empty_sha,
                "stdout_payload": relative,
                "started_utc": utc(second),
                "finished_utc": utc(second + 1),
                "exit_code": 0,
                "timed_out": False,
                "process_group_complete": True,
            })

    def _build_self_tests(self):
        environment = {
            "PATH": "/usr/bin:/bin",
            "LANG": "C.UTF-8",
            "LC_ALL": "C.UTF-8",
            "CP2_SELF_TEST": "1",
            "CP2_FORBID_BAG_ACCESS": "1",
        }
        environment_sha = command_environment_sha256(environment)
        self.self_test_environment_record = {
            "environment_id": "readiness_self_test_v1",
            "variables": [
                {"name": name, "value": environment[name]}
                for name in sorted(environment, key=lambda value: value.encode("utf-8"))
            ],
            "canonical_sha256": environment_sha,
        }
        entry_by_path = {entry["path"]: entry for entry in self.context["entries"]}
        self.self_tests = []
        for index, path in enumerate(verify_report.READINESS_ENTRYPOINTS):
            names = list(verify_report._actual_expected_readiness_cases()[path])
            result = passing_self_test_result(path, names, index)
            stdout = canonical_json(result) + b"\n"
            stderr = b""
            stdout_relative = "readiness/self_tests/{:02d}.stdout".format(index)
            stderr_relative = "readiness/self_tests/{:02d}.stderr".format(index)
            self._write(stdout_relative, stdout)
            self._write(stderr_relative, stderr)
            argv = ["/proc/self/fd/{}".format(10 + index), "--self-test"]
            if path.endswith(".py"):
                argv = ["/usr/bin/python3", "-I", "-B"] + argv
            second = 22 + 2 * index
            self.self_tests.append({
                "index": index,
                "path": path,
                "argv": argv,
                "cwd": "/tmp",
                "entrypoint_sha256": entry_by_path[path]["sha256"],
                "started_utc": utc(second),
                "finished_utc": utc(second + 1),
                "environment_sha256": environment_sha,
                "exit_code": 0,
                "timed_out": False,
                "process_group_complete": True,
                "stdout": stdout_relative,
                "stdout_sha256": sha256(stdout),
                "stderr": stderr_relative,
                "stderr_sha256": sha256(stderr),
                "expected_case_names": names,
                "result": result,
                "bag_provider_calls": 0,
                "temporary_root_removed": True,
            })

    def _build_unit_evidence(self):
        self.unit_artifact = self.parent / "unit-anchor"
        self.unit_artifact.mkdir(mode=0o700)
        unit_report_bytes = canonical_json({
            "record_type": "synthetic_unit_anchor",
            "schema_version": 1,
        }) + b"\n"
        unit_report = self.unit_artifact / verify_report.REPORT_NAME
        unit_report.write_bytes(unit_report_bytes)
        self.unit_manifest_sha = sha256(b"synthetic external manifest anchor")
        environment = {"PATH": "/usr/bin:/bin", "LANG": "C", "LC_ALL": "C"}
        self.unit_environment_sha = command_environment_sha256(environment)
        self.unit_environment_record = {
            "environment_id": "unit_verifier_v1",
            "variables": [
                {"name": name, "value": environment[name]}
                for name in sorted(environment, key=lambda value: value.encode("utf-8"))
            ],
            "canonical_sha256": self.unit_environment_sha,
        }
        result = {
            "commit": self.commit,
            "passed": True,
            "record_type": "cp2_prevalidated_unit_verification_result",
            "schema_version": 1,
            "tree": self.tree,
        }
        stdout = canonical_json(result) + b"\n"
        stderr = b""
        stdout_relative = "readiness/unit_verifier.stdout"
        stderr_relative = "readiness/unit_verifier.stderr"
        self._write(stdout_relative, stdout)
        self._write(stderr_relative, stderr)
        self.unit_verification = {
            "argv": [
                "/usr/bin/python3", "-I", "-B", "/proc/self/fd/30",
                "--verify-unit-anchor-prevalidated",
                "/tmp/schurvio-cp2-readiness-synthetic/unit-artifact-frozen",
                "--expected-manifest-sha256", self.unit_manifest_sha,
            ],
            "cwd": "/tmp",
            "environment": environment,
            "started_utc": utc(44),
            "finished_utc": utc(45),
            "exit_code": 0,
            "timed_out": False,
            "process_group_complete": True,
            "stdout": stdout_relative,
            "stdout_sha256": sha256(stdout),
            "stderr": stderr_relative,
            "stderr_sha256": sha256(stderr),
            "source_context_sha256": self.manifest["readiness/source_context.json"],
        }
        self.unit_anchor = {
            "artifact": str(self.unit_artifact),
            "manifest_sha256": self.unit_manifest_sha,
            "tested_commit": self.commit,
            "tested_tree": self.tree,
            "report_sha256": sha256(unit_report_bytes),
            "verified": True,
        }

    def _build_barrier_and_provenance(self):
        def path(name):
            return "readiness/{}.bin".format(name)

        self.barrier = {
            "schema_version": 1,
            "record_type": "readiness_barrier",
            "entrypoints": copy.deepcopy(self.context["entrypoints"]),
            "source_before_sha256": self.manifest[path("source_before")],
            "build_before_sha256": self.manifest[path("build_before")],
            "source_before_payload": path("source_before"),
            "build_before_payload": path("build_before"),
            "results_before_payload": path("results_before"),
            "results_before_sha256": self.manifest[path("results_before")],
            "testing_before_payload": path("testing_before"),
            "testing_before_sha256": self.manifest[path("testing_before")],
            "self_tests": copy.deepcopy(self.self_tests),
            "source_after_payload": path("source_after"),
            "source_after_sha256": self.manifest[path("source_after")],
            "build_after_payload": path("build_after"),
            "build_after_sha256": self.manifest[path("build_after")],
            "results_after_payload": path("results_after"),
            "results_after_sha256": self.manifest[path("results_after")],
            "testing_after_payload": path("testing_after"),
            "testing_after_sha256": self.manifest[path("testing_after")],
            "post_lock_payload": path("post_lock"),
            "post_lock_recheck_sha256": self.manifest[path("post_lock")],
            "post_unit_payload": path("post_unit"),
            "post_unit_recheck_sha256": self.manifest[path("post_unit")],
            "source_context_payload": "readiness/source_context.json",
            "source_context_sha256": self.manifest["readiness/source_context.json"],
            "data_lock": {
                "path": "/tmp/schurvio-lite-cp2-data.lock",
                "device": 1,
                "inode": 2,
                "mode": 0o600,
                "owner_uid": os.geteuid(),
                "link_count": 1,
                "acquired_exclusive": True,
            },
            "readiness_git_environment": copy.deepcopy(self.git_environment_record),
            "readiness_git_commands": copy.deepcopy(self.git_commands),
            "unit_verification": copy.deepcopy(self.unit_verification),
            "unit_artifact": str(self.unit_artifact),
            "unit_manifest_sha256": self.unit_manifest_sha,
            "unit_tested_commit": self.commit,
            "unit_tested_tree": self.tree,
            "bag_provider_calls": 0,
            "passed": True,
        }
        self._commit_barrier()
        entry_by_path = {
            entry["path"]: entry for entry in self.context["entries"]
        }
        contracts = [
            {"path": relative, "sha256": entry_by_path[relative]["sha256"]}
            for relative in sorted(
                self.contract_inputs, key=lambda value: value.encode("utf-8")
            )
        ]
        self.provenance = {
            "source_commit": self.commit,
            "source_tree": self.tree,
            "branch": verify_report.EXPECTED_BRANCH,
            "source_archive": self.SOURCE_ARCHIVE,
            "contracts": contracts,
            "entrypoints": [
                {"path": entry["path"], "sha256": entry["sha256"],
                 "git_blob": entry["git_blob"]}
                for entry in self.context["entrypoints"]
            ],
            "environment": {"classes": sorted(
                [copy.deepcopy(self.git_environment_record),
                 copy.deepcopy(self.self_test_environment_record),
                 copy.deepcopy(self.unit_environment_record)],
                key=lambda record: record["environment_id"].encode("utf-8"),
            )},
            "file_inventory": [],
        }
        self._refresh_inventory()
        self.commands = [self._unit_command_zero()]

    def _unit_command_zero(self):
        unit = self.barrier["unit_verification"]
        return {
            "schema_version": 1,
            "record_type": "command",
            "command_id": 0,
            "phase": "readiness",
            "sequence_index": None,
            "pair_index": None,
            "run_index": None,
            "argv": copy.deepcopy(unit["argv"]),
            "cwd": unit["cwd"],
            "environment_sha256": self.unit_environment_sha,
            "started_utc": unit["started_utc"],
            "finished_utc": unit["finished_utc"],
            "exit_code": unit["exit_code"],
            "timed_out": unit["timed_out"],
            "stdout": unit["stdout"],
            "stdout_sha256": unit["stdout_sha256"],
            "stderr": unit["stderr"],
            "stderr_sha256": unit["stderr_sha256"],
        }

    def _commit_barrier(self):
        self._write("readiness/barrier.json", canonical_json(self.barrier))

    def _refresh_inventory(self):
        readiness_paths = sorted(
            (path for path in self.manifest if path.startswith("readiness/")),
            key=lambda value: value.encode("utf-8"),
        )
        self.provenance["file_inventory"] = [
            {"path": path, "role": "readiness", "mode": 0o444}
            for path in readiness_paths
        ]

    def _stub_unit_verifier(self, artifact, manifest_sha, context, quiet=False):
        if (
            Path(artifact) != self.unit_artifact
            or manifest_sha != self.unit_manifest_sha
            or context != self.context
            or quiet is not True
        ):
            return 1, ["synthetic unit verifier binding differs"]
        return 0, []

    @contextlib.contextmanager
    def policy(self):
        with mock.patch.object(verify_report, "SOURCE_INPUTS", self.source_inputs), \
             mock.patch.object(verify_report, "CONTRACT_INPUTS", self.contract_inputs), \
             mock.patch.object(
                 verify_report,
                 "FROZEN_CP2_C_APPROVAL_BINDING",
                 self.approval_binding,
             ), \
             mock.patch.object(
                 verify_report,
                 "FROZEN_CP2_C_APPROVAL_RECORDS",
                 {},
             ), \
             mock.patch.object(
                 verify_report,
                 "FROZEN_CP2_COMPLETION_AUTHORIZATION_BINDING",
                 verify_report.FROZEN_CP2_COMPLETION_AUTHORIZATION_BINDING,
             ), \
             mock.patch.object(
                 verify_report,
                 "FROZEN_CP2_COMPLETION_AUTHORIZATION_RECORD",
                 verify_report.FROZEN_CP2_COMPLETION_AUTHORIZATION_RECORD,
             ), \
             mock.patch.object(
                 verify_report,
                 "verify_unit_anchor_prevalidated",
                 self._stub_unit_verifier,
             ):
            yield

    def validate(self):
        barrier, _, unit_environment_sha = (
            verify_report._actual_validate_source_unit_approval_binding(
                self.artifact,
                self.manifest,
                self.provenance,
                self.unit_anchor,
                "readiness/barrier.json",
            )
        )
        verify_report._actual_validate_readiness_command_zero(
            self.commands,
            self.provenance,
            barrier,
            unit_environment_sha,
        )

    def commit_changed_barrier(self):
        self._commit_barrier()

    def replace_readiness_payload(self, relative, content, update_barrier=None):
        self._write(relative, content)
        if update_barrier is not None:
            self.barrier[update_barrier] = self.manifest[relative]
        self._commit_barrier()

    def replace_git_output(self, index, content, coordinate=True):
        relative = "readiness/git/{:02d}.stdout".format(index)
        self._write(relative, content)
        if coordinate:
            self.barrier["readiness_git_commands"][index]["stdout_sha256"] = sha256(content)
        self._commit_barrier()

    def mutate(self, name):
        if name == "barrier_schema_bool":
            self.barrier["schema_version"] = True
        elif name == "barrier_extra_key":
            self.barrier["unexpected"] = 1
        elif name == "context_schema_bool":
            self.context["schema_version"] = True
            content = canonical_json(self.context)
            self.replace_readiness_payload(
                "readiness/source_context.json", content, "source_context_sha256"
            )
            self.barrier["unit_verification"]["source_context_sha256"] = sha256(content)
        elif name == "context_missing_field":
            content = canonical_json({
                key: value for key, value in self.context.items() if key != "branch"
            })
            self.replace_readiness_payload(
                "readiness/source_context.json", content, "source_context_sha256"
            )
            self.barrier["unit_verification"]["source_context_sha256"] = sha256(content)
        elif name == "context_duplicate_key":
            valid = canonical_json(self.context)
            content = b'{"branch":"duplicate",' + valid[1:]
            self.replace_readiness_payload(
                "readiness/source_context.json", content, "source_context_sha256"
            )
            self.barrier["unit_verification"]["source_context_sha256"] = sha256(content)
        elif name == "context_noncanonical":
            content = json.dumps(self.context, indent=2, sort_keys=True).encode("utf-8")
            self.replace_readiness_payload(
                "readiness/source_context.json", content, "source_context_sha256"
            )
            self.barrier["unit_verification"]["source_context_sha256"] = sha256(content)
        elif name == "context_entry_reordered":
            changed = copy.deepcopy(self.context)
            changed["entries"][0], changed["entries"][1] = (
                changed["entries"][1], changed["entries"][0]
            )
            content = canonical_json(changed)
            self.replace_readiness_payload(
                "readiness/source_context.json", content, "source_context_sha256"
            )
            self.barrier["unit_verification"]["source_context_sha256"] = sha256(content)
        elif name == "archive_payload_corrupt":
            path = self.artifact / self.SOURCE_ARCHIVE
            path.chmod(0o600)
            data = bytearray(path.read_bytes())
            needle = self.source_contents[self.APPROVAL_PATH]
            offset = bytes(data).find(needle)
            if offset < 0:
                raise RuntimeError("synthetic source archive lost its approval payload")
            data[offset] ^= 1
            path.write_bytes(bytes(data))
            path.chmod(0o444)
        elif name == "approval_sha_mismatch":
            self.approval_binding[self.APPROVAL_PATH]["sha256"] = "0" * 64
        elif name == "contract_projection_mismatch":
            self.provenance["contracts"][0]["sha256"] = "0" * 64
        elif name == "git_missing_command":
            self.barrier["readiness_git_commands"].pop()
        elif name == "git_reordered_command":
            commands = self.barrier["readiness_git_commands"]
            commands[0], commands[1] = commands[1], commands[0]
        elif name == "git_prefix":
            self.barrier["readiness_git_commands"][0]["argv"][0] = "/bin/false"
        elif name == "git_suffix":
            self.barrier["readiness_git_commands"][0]["argv"][-1] = "--cached"
        elif name == "git_environment_value":
            record = self.barrier["readiness_git_environment"]
            next(item for item in record["variables"] if item["name"] == "LANG")["value"] = "C"
        elif name == "git_cwd":
            self.barrier["readiness_git_commands"][0]["cwd"] = "/tmp"
        elif name == "git_stdin_sha":
            self.barrier["readiness_git_commands"][2]["stdin_sha256"] = "0" * 64
        elif name == "git_stdout_sha":
            self.barrier["readiness_git_commands"][3]["stdout_sha256"] = "0" * 64
        elif name == "git_stderr_sha":
            self.barrier["readiness_git_commands"][0]["stderr_sha256"] = "0" * 64
        elif name == "git_nonzero_exit":
            self.barrier["readiness_git_commands"][0]["exit_code"] = 1
        elif name == "git_timeout":
            self.barrier["readiness_git_commands"][0]["timed_out"] = True
        elif name == "git_group_incomplete":
            self.barrier["readiness_git_commands"][0]["process_group_complete"] = False
        elif name == "git_overlap":
            self.barrier["readiness_git_commands"][1]["started_utc"] = utc(0)
        elif name == "git_cat_payload":
            self.barrier["readiness_git_commands"][2]["stdout_payload"] = (
                "readiness/git/02.stdout"
            )
        elif name == "git_missing_attachment":
            path = self.artifact / "readiness/git/01.stdout"
            path.chmod(0o600)
            path.unlink()
        elif name == "git_path_no_nul":
            self.replace_git_output(1, b"build/cache/a.bin")
            return
        elif name == "git_path_duplicate":
            self.replace_git_output(
                1, b"build/cache/a.bin\0build/cache/a.bin\0build/link\0"
            )
            return
        elif name == "git_path_unsafe_root":
            self.replace_git_output(1, b"outside/file\0")
            return
        elif name == "git_path_control":
            self.replace_git_output(1, b"build/.gitignore\0")
            return
        elif name == "git_other_population":
            self.replace_git_output(1, b"build/cache/a.bin\0")
            return
        elif name == "git_ignored_not_subset":
            self.replace_git_output(4, b"build/not-present\0")
            return
        elif name == "snapshot_source_mismatch":
            self.replace_readiness_payload(
                "readiness/source_after.bin", self.snapshot_bytes["source_after"] + b"x",
                "source_after_sha256",
            )
            return
        elif name == "snapshot_build_mismatch":
            self.replace_readiness_payload(
                "readiness/build_after.bin", self.snapshot_bytes["results_after"],
                "build_after_sha256",
            )
            return
        elif name == "snapshot_results_mismatch":
            self.replace_readiness_payload(
                "readiness/results_after.bin", self.snapshot_bytes["testing_after"],
                "results_after_sha256",
            )
            return
        elif name == "snapshot_testing_mismatch":
            self.replace_readiness_payload(
                "readiness/testing_after.bin", self.snapshot_bytes["results_after"],
                "testing_after_sha256",
            )
            return
        elif name == "post_lock_wrong_tag":
            content = self.snapshot_bytes["post_lock"].replace(
                lp(b"post_lock"), lp(b"source"), 1
            )
            self.replace_readiness_payload(
                "readiness/post_lock.bin", content, "post_lock_recheck_sha256"
            )
            return
        elif name == "post_unit_mismatch":
            self.replace_readiness_payload(
                "readiness/post_unit.bin", self.snapshot_bytes["post_unit"] + b"x",
                "post_unit_recheck_sha256",
            )
            return
        elif name == "lock_path":
            self.barrier["data_lock"]["path"] = "/tmp/other.lock"
        elif name == "lock_mode":
            self.barrier["data_lock"]["mode"] = 0o644
        elif name == "selftest_order":
            tests = self.barrier["self_tests"]
            tests[0], tests[1] = tests[1], tests[0]
        elif name == "selftest_argv":
            self.barrier["self_tests"][1]["argv"][0] = "/usr/bin/python3.8"
        elif name == "selftest_cwd":
            self.barrier["self_tests"][0]["cwd"] = "/var/tmp"
        elif name == "selftest_environment":
            self.barrier["self_tests"][0]["environment_sha256"] = "0" * 64
        elif name == "selftest_overlap":
            self.barrier["self_tests"][1]["started_utc"] = utc(22)
        elif name == "selftest_timeout":
            self.barrier["self_tests"][0]["timed_out"] = True
        elif name == "selftest_group":
            self.barrier["self_tests"][0]["process_group_complete"] = False
        elif name == "selftest_provider":
            self.barrier["self_tests"][0]["bag_provider_calls"] = 1
        elif name == "selftest_case_inventory":
            test = self.barrier["self_tests"][0]
            names = test["expected_case_names"][:-1]
            result = passing_self_test_result(test["path"], names, 0)
            content = canonical_json(result) + b"\n"
            self._write(test["stdout"], content)
            test["stdout_sha256"] = sha256(content)
            test["expected_case_names"] = names
            test["result"] = result
            self._commit_barrier()
            return
        elif name == "unit_argv":
            self.barrier["unit_verification"]["argv"][0] = "/usr/bin/env"
        elif name == "unit_environment":
            self.barrier["unit_verification"]["environment"]["LANG"] = "C.UTF-8"
        elif name == "unit_context_sha":
            self.barrier["unit_verification"]["source_context_sha256"] = "0" * 64
        elif name == "unit_timeout":
            self.barrier["unit_verification"]["timed_out"] = True
        elif name == "unit_result_bool_schema":
            result = {
                "commit": self.commit,
                "passed": True,
                "record_type": "cp2_prevalidated_unit_verification_result",
                "schema_version": True,
                "tree": self.tree,
            }
            content = canonical_json(result) + b"\n"
            self.replace_readiness_payload(
                "readiness/unit_verifier.stdout", content, None
            )
            self.barrier["unit_verification"]["stdout_sha256"] = sha256(content)
            self._commit_barrier()
            return
        elif name == "command_zero_duplicate":
            self.commands.append(copy.deepcopy(self.commands[0]))
        elif name == "command_zero_projection":
            self.commands[0]["argv"][-1] = "0" * 64
        elif name == "namespace_extra":
            self._write("readiness/orphan.bin", b"orphan")
            self._refresh_inventory()
            return
        elif name == "namespace_alias":
            self.barrier["source_after_payload"] = self.barrier["source_before_payload"]
        elif name == "inventory_role":
            next(
                record for record in self.provenance["file_inventory"]
                if record["path"] == "readiness/post_unit.bin"
            )["role"] = "source"
            return
        elif name == "inventory_mode":
            next(
                record for record in self.provenance["file_inventory"]
                if record["path"] == "readiness/post_unit.bin"
            )["mode"] = 0o644
            return
        elif name == "namespace_symlink":
            path = self.artifact / "readiness/post_unit.bin"
            path.chmod(0o600)
            path.unlink()
            path.symlink_to("post_lock.bin")
            return
        elif name == "namespace_hardlink":
            path = self.artifact / "readiness/post_unit.bin"
            path.chmod(0o600)
            path.unlink()
            os.link(
                str(self.artifact / "readiness/post_lock.bin"),
                str(path),
            )
            return
        else:
            raise ValueError("unknown readiness mutation: " + name)
        self._commit_barrier()

class ActualReadinessBindingTests(unittest.TestCase):
    maxDiff = None

    def fixture(self, temporary):
        return ActualReadinessFixture(temporary)

    def assert_mutations_rejected(self, names):
        for name in names:
            with self.subTest(mutation=name):
                with tempfile.TemporaryDirectory(
                    prefix="cp2-actual-readiness-binding-", dir="/tmp"
                ) as temporary:
                    fixture = self.fixture(temporary)
                    fixture.mutate(name)
                    with fixture.policy():
                        with self.assertRaises(
                            (verify_report.ActualVerificationError, ValueError),
                            msg="production readiness verifier accepted " + name,
                        ):
                            fixture.validate()

    def test_valid_fixture_passes(self):
        with tempfile.TemporaryDirectory(
            prefix="cp2-actual-readiness-binding-", dir="/tmp"
        ) as temporary:
            fixture = self.fixture(temporary)
            with fixture.policy():
                fixture.validate()
                schema = verify_report._actual_load_module("cp2_schema")
                self.assertTrue(callable(schema.command_environment_sha256))

    def test_approved_cp2_c_actual_paths_reach_only_the_bound_entry_boundaries(self):
        arguments = (
            "--unit-artifact", "/tmp/cp2-c-synthetic-unit",
            "--unit-manifest-sha256", "0" * 64,
        )
        stderr = io.StringIO()
        readiness_loader = mock.Mock(
            side_effect=RuntimeError("synthetic approved readiness boundary")
        )
        with mock.patch.object(
                run_recorded, "_load_readiness_by_descriptor",
                readiness_loader), \
                contextlib.redirect_stderr(stderr):
            status = run_recorded._actual_mode(arguments)
        self.assertEqual(status, getattr(os, "EX_CONFIG", 78))
        readiness_loader.assert_called_once_with()
        self.assertIn("synthetic approved readiness boundary", stderr.getvalue())

        artifact_scanner = mock.Mock(
            side_effect=AssertionError("synthetic approved artifact boundary")
        )
        with mock.patch.object(
                verify_report, "_actual_scan_and_verify_manifest",
                artifact_scanner):
            with self.assertRaisesRegex(AssertionError, "approved artifact boundary"):
                verify_report.verify_recorded_artifact(
                    "/tmp/cp2-c-synthetic-artifact", "1" * 64)
        artifact_scanner.assert_called_once()

        class SyntheticAuthorization:
            def __init__(self, root):
                self.root = Path(root)
                self.closed = False
                self.descriptors = []

            def revalidate(self):
                if self.closed:
                    raise RuntimeError("synthetic authorization is closed")

            def duplicate_source_fd(self, relative):
                self.revalidate()
                if relative not in {
                    path for _, path in run_recorded.POSTAUTHORIZATION_MODULE_SOURCES
                }:
                    raise RuntimeError("synthetic source is outside the allowlist")
                descriptor = os.open(
                    str(self.root.joinpath(*relative.split("/"))),
                    os.O_RDONLY | os.O_CLOEXEC,
                )
                self.descriptors.append(descriptor)
                return descriptor

        with tempfile.TemporaryDirectory(
            prefix="cp2-held-module-loader-", dir="/tmp"
        ) as temporary:
            root = Path(temporary)
            source_directory = root / "scripts/cp2"
            source_directory.mkdir(parents=True)
            schema_path = source_directory / "cp2_schema.py"
            capsule_path = source_directory / "cp2_capsule.py"
            campaign_path = source_directory / "cp2_recorded_campaign.py"
            schema_path.write_bytes(b"TOKEN = 'held-schema'\n")
            capsule_path.write_bytes(
                b"import cp2_schema\nTOKEN = cp2_schema.TOKEN + '-capsule'\n"
            )
            campaign_path.write_bytes(
                b"import cp2_schema\nimport cp2_capsule\n"
                b"TOKEN = cp2_capsule.TOKEN + '-campaign'\n"
            )
            authorization = SyntheticAuthorization(root)
            modules = run_recorded._HeldPostauthorizationModules(
                root, authorization
            )
            descriptors = tuple(authorization.descriptors)
            try:
                self.assertEqual(
                    modules.campaign.TOKEN, "held-schema-capsule-campaign"
                )
                modules.revalidate()
                with schema_path.open("ab") as stream:
                    stream.write(b"MUTATION = True\n")
                with self.assertRaises((run_recorded.Rejection, RuntimeError)):
                    modules.revalidate()
            finally:
                modules.close()
            self.assertNotIn("cp2_schema", sys.modules)
            self.assertNotIn("cp2_capsule", sys.modules)
            self.assertNotIn("cp2_recorded_campaign", sys.modules)
            for descriptor in descriptors:
                with self.assertRaises(OSError):
                    os.fstat(descriptor)

            schema_path.write_bytes(b"TOKEN = 'held-schema'\n")
            capsule_path.write_bytes(
                b"import cp2_schema\nTOKEN = cp2_schema.TOKEN + '-capsule'\n"
            )
            campaign_path.write_bytes(b"")
            failed_authorization = SyntheticAuthorization(root)
            with self.assertRaisesRegex(
                run_recorded.Rejection,
                "cp2_recorded_campaign source identity is invalid",
            ):
                run_recorded._HeldPostauthorizationModules(
                    root, failed_authorization
                )
            self.assertNotIn("cp2_schema", sys.modules)
            self.assertNotIn("cp2_capsule", sys.modules)
            self.assertNotIn("cp2_recorded_campaign", sys.modules)
            for descriptor in failed_authorization.descriptors:
                with self.assertRaises(OSError):
                    os.fstat(descriptor)

            sentinel = object()
            with mock.patch.dict(sys.modules, {"cp2_schema": sentinel}):
                with self.assertRaises(run_recorded.Rejection):
                    run_recorded._HeldPostauthorizationModules(
                        root, SyntheticAuthorization(root)
                    )
                self.assertIs(sys.modules["cp2_schema"], sentinel)
                self.assertNotIn("cp2_capsule", sys.modules)
                self.assertNotIn("cp2_recorded_campaign", sys.modules)

        # Exercise the exact production module bytes as one dependency-closed
        # descriptor load.  This catches an accidental workspace import or a
        # local dependency that isolated Python cannot resolve before any
        # recorded-input capability is involved.
        repository_root = CP2_DIRECTORY.parents[1]
        production_authorization = SyntheticAuthorization(repository_root)
        production_modules = run_recorded._HeldPostauthorizationModules(
            repository_root, production_authorization
        )
        try:
            self.assertTrue(
                callable(production_modules.campaign.execute_recorded_campaign)
            )
            production_modules.revalidate()
        finally:
            production_modules.close()
        self.assertNotIn("cp2_schema", sys.modules)
        self.assertNotIn("cp2_capsule", sys.modules)
        self.assertNotIn("cp2_recorded_campaign", sys.modules)

        # Once the authorization reports its exact held inode at the durable
        # published boundary, even a campaign return-state gap and later
        # cleanup errors are diagnostic only; they may not relabel the
        # already-published artifact as a failed execution.
        class PublishedBinding:
            def __init__(self):
                self.close_calls = 0

            def revalidate(self):
                return None

            def close(self):
                self.close_calls += 1
                raise RuntimeError("synthetic binding cleanup")

        class PublishedAuthorization:
            def __init__(self):
                self.close_calls = 0
                self.publication_query_calls = 0

            def read_registry_once(self):
                return b"synthetic authorized registry buffer"

            def current_output_publication_state(self):
                self.publication_query_calls += 1
                if self.publication_query_calls == 1:
                    raise KeyboardInterrupt(
                        "synthetic publication-query store gap"
                    )
                return "published"

            def close(self):
                self.close_calls += 1
                raise RuntimeError("synthetic authorization cleanup")

        class PublishedReadiness:
            EXPECTED_CASE_NAMES_BY_ENTRYPOINT = {}
            CP1_AUTHORIZATION_COMMIT = "0" * 40

            def __init__(self, authorization):
                self.authorization = authorization

            def run_readiness_barrier(self, **kwargs):
                del kwargs
                return self.authorization

        class PublishedCampaign:
            @staticmethod
            def execute_recorded_campaign(**kwargs):
                kwargs["prepublication_guard"]()
                # Model an asynchronous exception after the campaign's
                # durable commit but before its return value reaches the
                # caller's local variable.
                raise KeyboardInterrupt("synthetic publish/return gap")

        class PublishedModules:
            def __init__(self):
                self.campaign = PublishedCampaign()
                self.close_calls = 0

            def revalidate(self):
                return None

            def close(self):
                self.close_calls += 1
                raise RuntimeError("synthetic module cleanup")

        published_binding = PublishedBinding()
        published_authorization = PublishedAuthorization()
        published_modules = PublishedModules()
        published_stderr = io.StringIO()
        with mock.patch.object(
            run_recorded,
            "_load_readiness_by_descriptor",
            return_value=(
                PublishedReadiness(published_authorization),
                published_binding,
            ),
        ), mock.patch.object(
            run_recorded,
            "_HeldPostauthorizationModules",
            return_value=published_modules,
        ), contextlib.redirect_stderr(published_stderr):
            published_status = run_recorded._actual_mode(arguments)
        self.assertEqual(published_status, 0)
        self.assertEqual(published_modules.close_calls, 1)
        self.assertEqual(published_authorization.close_calls, 1)
        self.assertEqual(published_authorization.publication_query_calls, 2)
        self.assertEqual(published_binding.close_calls, 1)
        self.assertIn("publication succeeded", published_stderr.getvalue())
        self.assertIn("synthetic publish/return gap", published_stderr.getvalue())
        self.assertIn(
            "synthetic publication-query store gap",
            published_stderr.getvalue(),
        )

    def test_context_archive_and_approval_mutations_fail(self):
        self.assert_mutations_rejected((
            "barrier_schema_bool",
            "barrier_extra_key",
            "context_schema_bool",
            "context_missing_field",
            "context_duplicate_key",
            "context_noncanonical",
            "context_entry_reordered",
            "archive_payload_corrupt",
            "approval_sha_mismatch",
            "contract_projection_mismatch",
        ))

    def test_git_command_and_output_mutations_fail(self):
        self.assert_mutations_rejected((
            "git_missing_command",
            "git_reordered_command",
            "git_prefix",
            "git_suffix",
            "git_environment_value",
            "git_cwd",
            "git_stdin_sha",
            "git_stdout_sha",
            "git_stderr_sha",
            "git_nonzero_exit",
            "git_timeout",
            "git_group_incomplete",
            "git_overlap",
            "git_cat_payload",
            "git_missing_attachment",
            "git_path_no_nul",
            "git_path_duplicate",
            "git_path_unsafe_root",
            "git_path_control",
            "git_other_population",
            "git_ignored_not_subset",
        ))

    def test_local_module_loader_binding_rejections(self):
        binding = {}
        for name, relative in verify_report._ACTUAL_LOCAL_MODULE_PATHS.items():
            path = CP2_DIRECTORY / Path(relative).name
            status_value = path.lstat()
            binding[name] = {
                "mode": 0o100755 if status_value.st_mode & 0o100 else 0o100644,
                "sha256": sha256(path.read_bytes()),
                "size": status_value.st_size,
            }

        def require_rejection(label, installed, cache, name):
            with self.subTest(binding=label), \
                 mock.patch.object(
                     verify_report, "_ACTUAL_MODULE_SOURCE_BINDING", installed
                 ), \
                 mock.patch.object(
                     verify_report,
                     "_ACTUAL_MODULE_SOURCE_BINDING_ORIGIN",
                     None if installed is None else "artifact_source_context",
                 ), \
                 mock.patch.object(verify_report, "_ACTUAL_MODULE_CACHE", cache):
                with self.assertRaises(verify_report.ActualVerificationError):
                    verify_report._actual_load_module(name)

        require_rejection("unbound", None, {}, "cp2_schema")
        require_rejection("nonallowlisted", copy.deepcopy(binding), {}, "not_allowed")
        for field, replacement in (
            ("sha256", "0" * 64),
            ("size", binding["cp2_schema"]["size"] + 1),
            (
                "mode",
                0o100755
                if binding["cp2_schema"]["mode"] == 0o100644
                else 0o100644,
            ),
        ):
            changed = copy.deepcopy(binding)
            changed["cp2_schema"][field] = replacement
            require_rejection("source-" + field, changed, {}, "cp2_schema")
        stale = mock.Mock()
        stale.__schurvio_source_binding__ = {
            "mode": 0o100644,
            "sha256": "f" * 64,
            "size": 1,
        }
        require_rejection(
            "cached-binding",
            copy.deepcopy(binding),
            {"cp2_schema": stale},
            "cp2_schema",
        )

    def test_snapshot_lock_and_postunit_mutations_fail(self):
        self.assert_mutations_rejected((
            "snapshot_source_mismatch",
            "snapshot_build_mismatch",
            "snapshot_results_mismatch",
            "snapshot_testing_mismatch",
            "post_lock_wrong_tag",
            "post_unit_mismatch",
            "lock_path",
            "lock_mode",
        ))

    def test_self_test_mutations_fail(self):
        self.assert_mutations_rejected((
            "selftest_order",
            "selftest_argv",
            "selftest_cwd",
            "selftest_environment",
            "selftest_overlap",
            "selftest_timeout",
            "selftest_group",
            "selftest_provider",
            "selftest_case_inventory",
        ))

    def test_unit_and_command_zero_mutations_fail(self):
        self.assert_mutations_rejected((
            "unit_argv",
            "unit_environment",
            "unit_context_sha",
            "unit_timeout",
            "unit_result_bool_schema",
            "command_zero_duplicate",
            "command_zero_projection",
        ))

    def test_namespace_and_inventory_mutations_fail(self):
        self.assert_mutations_rejected((
            "namespace_extra",
            "namespace_alias",
            "inventory_role",
            "inventory_mode",
            "namespace_symlink",
            "namespace_hardlink",
        ))

    @staticmethod
    def _start_python(source):
        return subprocess.Popen(
            ["/usr/bin/python3", "-I", "-B", "-c", source],
            cwd="/tmp",
            env={"PATH": "/usr/bin:/bin", "LANG": "C", "LC_ALL": "C"},
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
            close_fds=True,
        )

    def test_owned_process_group_timeout_is_reaped(self):
        process = self._start_python("import time; time.sleep(60)")
        return_code, timed_out, descendants = (
            verify_report._actual_wait_owned_process_group(
                process, 0.02, "synthetic timeout child"
            )
        )
        self.assertTrue(timed_out)
        self.assertFalse(descendants)
        self.assertLess(return_code, 0)
        self.assertFalse(verify_report._actual_process_group_exists(process.pid))

    def test_owned_process_group_baseexception_is_reaped(self):
        process = self._start_python("import time; time.sleep(60)")
        real_wait = process.wait
        calls = [0]

        def interrupted_wait(*args, **kwargs):
            calls[0] += 1
            if calls[0] == 1:
                raise KeyboardInterrupt("synthetic wait interruption")
            return real_wait(*args, **kwargs)

        process.wait = interrupted_wait
        with self.assertRaises(KeyboardInterrupt):
            verify_report._actual_wait_owned_process_group(
                process, 1.0, "synthetic interrupted child"
            )
        self.assertIsNotNone(process.returncode)
        self.assertFalse(verify_report._actual_process_group_exists(process.pid))

    def test_owned_process_group_stubborn_descendant_is_detected(self):
        source = (
            "import os,time\n"
            "child=os.fork()\n"
            "if child==0:\n"
            " signal=None\n"
            " time.sleep(60)\n"
            "os._exit(0)\n"
        )
        process = self._start_python(source)
        return_code, timed_out, descendants = (
            verify_report._actual_wait_owned_process_group(
                process, 2.0, "synthetic descendant child"
            )
        )
        self.assertEqual(return_code, 0)
        self.assertFalse(timed_out)
        self.assertTrue(descendants)
        self.assertFalse(verify_report._actual_process_group_exists(process.pid))


if __name__ == "__main__":
    unittest.main()
